FROM maven:3.9.7-eclipse-temurin-21 AS build
WORKDIR /app
COPY . .
# We use the fast build flags to ensure it builds under Render's memory constraints
RUN mvn clean package -pl torrent-monolith -am -DskipTests

FROM eclipse-temurin:21-jre-alpine
WORKDIR /app
COPY --from=build /app/torrent-monolith/target/*-SNAPSHOT.jar app.jar
EXPOSE 8080
# Restricting heap to 256m so it fits perfectly in Render's 512m Free Tier
ENV JAVA_TOOL_OPTIONS="-Xmx256m -Xms128m"
ENTRYPOINT ["java", "-jar", "app.jar"]
