services:
  - type: redis
    name: torrent-redis
  - type: web
    name: torrent-backend
    env: docker
    dockerfilePath: ./Dockerfile.backend
    envVars:
      - key: DB_HOST
        fromDatabase:
          name: torrent-db
          property: host
      - key: DB_PORT
        fromDatabase:
          name: torrent-db
          property: port
      - key: DB_USER
        fromDatabase:
          name: torrent-db
          property: user
      - key: DB_PASS
        fromDatabase:
          name: torrent-db
          property: password
      - key: DB_NAME
        fromDatabase:
          name: torrent-db
          property: database
      - key: REDIS_HOST
        fromService:
          type: redis
          name: torrent-redis
          property: host
      - key: REDIS_PORT
        fromService:
          type: redis
          name: torrent-redis
          property: port
      - key: KAFKA_BOOTSTRAP_SERVERS
        fromService:
          type: pserv
          name: torrent-kafka
          property: hostport
      - key: KAFKA_SECURITY_PROTOCOL
        value: PLAINTEXT
    
  - type: web
    name: torrent-console
    env: docker
    dockerfilePath: ./Dockerfile.console
    envVars:
      - key: VITE_API_URL_BASE
        fromService:
          type: web
          name: torrent-backend
          property: url

  - type: web
    name: torrent-ui
    env: docker
    dockerfilePath: ./Dockerfile.ui
    envVars:
      - key: VITE_API_URL_BASE
        fromService:
          type: web
          name: torrent-backend
          property: url

  - type: pserv
    name: torrent-kafka
    env: image
    image:
      url: docker.io/bitnami/kafka:3.5
    envVars:
      - key: KAFKA_CFG_ZOOKEEPER_CONNECT
        fromService:
          type: pserv
          name: torrent-zookeeper
          property: hostport
      - key: ALLOW_PLAINTEXT_LISTENER
        value: yes
      - key: KAFKA_CFG_LISTENERS
        value: PLAINTEXT://:9092
      - key: KAFKA_CFG_ADVERTISED_LISTENERS
        value: PLAINTEXT://${RENDER_SERVICE_NAME}:${PORT}
    
  - type: pserv
    name: torrent-zookeeper
    env: image
    image:
      url: docker.io/bitnami/zookeeper:3.8
    envVars:
      - key: ALLOW_ANONYMOUS_LOGIN
        value: yes

databases:
  - name: torrent-db
    databaseName: torrent
    user: torrent
