services:
  - type: web
    name: torrent-backend
    env: docker
    plan: free
    dockerfilePath: ./Dockerfile.backend
    envVars:
      - key: DB_HOST
        fromDatabase:
          name: torrent-db
          property: host
      - key: DB_PORT
        fromDatabase:
          name: torrent-db
          property: port
      - key: DB_USER
        fromDatabase:
          name: torrent-db
          property: user
      - key: DB_PASS
        fromDatabase:
          name: torrent-db
          property: password
      - key: DB_NAME
        fromDatabase:
          name: torrent-db
          property: database
      - key: REDIS_HOST
        sync: false
      - key: REDIS_PORT
        sync: false
      - key: REDIS_PASSWORD
        sync: false
      - key: REDIS_SSL
        value: true
      - key: KAFKA_BOOTSTRAP_SERVERS
        sync: false
      - key: KAFKA_SECURITY_PROTOCOL
        value: SASL_SSL
      - key: KAFKA_SASL_MECHANISM
        value: SCRAM-SHA-256
      - key: KAFKA_JAAS_CONFIG
        sync: false
    
  - type: web
    name: torrent-console
    env: docker
    plan: free
    dockerfilePath: ./Dockerfile.console
    envVars:
      - key: VITE_API_URL_BASE
        sync: false

  - type: web
    name: torrent-ui
    env: docker
    plan: free
    dockerfilePath: ./Dockerfile.ui
    envVars:
      - key: VITE_API_URL_BASE
        sync: false

databases:
  - name: torrent-db
    databaseName: torrent
    user: torrent
    plan: free
